### ISSUE TITLE
Feat: Favicon missing 

### ISSUE THREAD

**Issue by Saifullah00** [mrsudarshanrai/QR-code-generator#11]
Favicon is missing, I have added it please assign it to me  so I can issue PR. 
![Qrcode](https://github.com/mrsudarshanrai/QR-code-generator/assets/78204201/3d5c2c2b-e72a-4c44-9c01-5f85d7409669)

Before : After

Happy Hactoberfest

**Comment by mrsudarshanrai** [comment]
Thank you for your contribution.
