### ISSUE TITLE
[Feature] Add hover effect and on Generate Qr Code

### ISSUE THREAD

**Issue by PankajKumar1947** [mrsudarshanrai/QR-code-generator#5]
![Screenshot (40)](https://github.com/mrsudarshanrai/QR-code-generator/assets/130830370/da30e698-4f02-43d4-889d-43e09b472e69)

**Comment by PankajKumar1947** [comment]
Please add hactoberfest labels and assign it to me

**Comment by mrsudarshanrai** [comment]
Thank you for your contribution.

**Comment by Saifullah00** [comment]
@mrsudarshanrai is there is any related queries, I will love to work on it under Hactoberfest.
