### ISSUE TITLE
Update in Readme.md

### ISSUE THREAD

**Issue by Saifullah00** [mrsudarshanrai/QR-code-generator#7]
@mrsudarshanrai your Readme.md is empty, for a project readme.md is valuable asset, If you assign I will work on it under Hactoberfest'23.
Thank you

**Comment by mrsudarshanrai** [comment]
Thanks for noticing, @Saifullah00, I welcome your help in enhancing the project's Readme.md during Hacktoberfest'23. Your contributions will be much appreciated.

**Comment by mrsudarshanrai** [comment]
https://github.com/mrsudarshanrai/QR-code-generator/pull/8
