### ISSUE TITLE
Handling Empty Input Fields

### ISSUE THREAD

**Issue by ayushichoudhary-19** [mrsudarshanrai/QR-code-generator#9]
**Description:**

The current implementation of the project does not handle empty input fields gracefully. When a user leaves the QR text or dimension input fields empty and clicks the button, the project proceeds to generate a QR code and download link with empty or undefined values. This behavior can lead to unexpected results and a poor user experience.

**Expected Behavior:**

When a user attempts to generate a QR code with empty input fields, the project should:
- Display an error message or provide feedback indicating that both QR text and dimension fields are required.
- Prevent the generation of a QR code and download link until valid input values are provided.

**Steps to Reproduce:**

1. Open the project with a web browser.
2. Leave the QR text input field empty.
3. Leave the dimension input field empty.
4. Click the button meant to generate the QR code.
5. Observe that the project proceeds to generate a QR code and download link without handling the empty input fields.

**Note:**

I would like to work on this issue. Please assign it to me.

**Comment by mrsudarshanrai** [comment]
@ayushichoudhary-19  
Thanks for your interest . This issue is now assigned to you. Looking forward to your contributions. Happy hacking! 🚀

**Comment by mrsudarshanrai** [comment]
https://github.com/mrsudarshanrai/QR-code-generator/pull/10

**Comment by ayushichoudhary-19** [comment]
Can you please tag this issue as `hacktoberfest` and `hacktoberfest-accepted`?
